FROM python:3.9-slim
EXPOSE 8001
WORKDIR /auth

RUN apt-get update && apt-get --yes upgrade

COPY ./requirements /auth/requirements
RUN pip install -r /auth/requirements/auth.txt --no-cache-dir

COPY ./auth /auth

CMD ["gunicorn", "main:app", "-b", "0.0.0.0:8001", "--reload"]
