FROM python:3.9-slim
EXPOSE 7777
WORKDIR /app

RUN apt-get update && apt-get --yes upgrade

COPY ./requirements /app/requirements
RUN pip install -r /app/requirements/ugc.txt --no-cache-dir

COPY ./app /app

CMD uvicorn main:app --host 0.0.0.0 --port 7777 --reload