# This workflow will install Python dependencies and lint with a variety of Python versions

name: PR workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # TO-DO uncomment the list behind, delete the one after it
        # python-version: [3.7, 3.8, 3.9]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Wemake Python Stylguide
      uses: wemake-services/wemake-python-styleguide@0.15.3
      continue-on-error: true
    - name: Mypy Check
      run: |
        mypy .
      continue-on-error: true
